apiVersion: v1
kind: ServiceAccount
metadata:
  name: check
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: check
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: check
    namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: check-test
  name: check-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        sidecar.istio.io/inject: "false"
      labels:
        app: check-test
    spec:
      serviceAccount: check
      containers:
        - image: registry.cn-shenzhen.aliyuncs.com/axd/check-test
          imagePullPolicy: Always
          name: check-test
